### PR TITLE
Added C6 for Teleinfo

### PR DESCRIPTION
**Pull request by hallard**
may need to add also this on tasmota-build so it can be auto build @Jason2866

### CODE REVIEW

**Comment by Jason2866** [comment]
Yes, it needs to be builded. Better add there first and let us merge this one after the build.

**Comment by hallard** [comment]
you want me do do it on tasmota-build? it's on special_builder branch?

**Comment by Jason2866** [comment]
Yes, add it here https://github.com/Jason2866/Tasmota-build/blob/special_builder/platformio_tasmota_cenv.ini
I will add to GH Actions build yml

**Comment by hallard** [comment]
Looks pretty new for me, does someting like that sounds good, not sure about `tasmota32_base`

```ini
[env:tasmota32c6-teleinfo]
extends                     = env:tasmota32c6-arduino30
build_flags                 = ${env:tasmota32_base.build_flags} -DCUSTOM_CONFIG_TELEINFO=true -DCUSTOM_CONFIG_REMOVALS=true
lib_extra_dirs              = lib/libesp32, lib/lib_basic, lib/lib_i2c, lib/lib_div, lib/lib_ssl, lib/lib_display
```

**Comment by Jason2866** [comment]
Add it and we will try ;-)  At first sight it looks okay.

**Pull request merged**
